name: continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install Dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Unit Tests
        run: pytest -v
